
dist: trusty
language: node_js
node_js:
  - "8"
sudo: required
addons:
  chrome: stable # have Travis install Chrome stable.
cache:
  directories:
  - node_modules
install:
  - npm install
  - npm install codecov -g
script:
  - npm run test
after_success:
  - codecov
env:
  CODECOV_TOKEN="3bca542c-6ada-4e15-bdca-804f851072b7"