
dist: trusty
language: node_js
node_js:
  - "8"
sudo: required
addons:
  chrome: stable # have Travis install Chrome stable.
install:
  - npm install
script:
  - npm run test
cache:
  directories:
  - node_modules
